<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="C:/Users/91966/APIRESTAUTOMTATION/src/test/java/RESTAssuredAPIAutomation/TestNG/Groups.java"
           tests="8"
           failures="1"
           errors="0"
           skipped="0"
           time="0.158">
    <properties></properties>

            <testcase
                name="smokeRun1"
                time="0.016"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">

            <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
                org.testng.Assert.fail(Assert.java:110)org.testng.Assert.failNotEquals(Assert.java:1577)org.testng.Assert.assertTrue(Assert.java:56)org.testng.Assert.assertTrue(Assert.java:66)RESTAssuredAPIAutomation.TestNG.Groups.smokeRun1(Groups.java:44)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)java.base/java.lang.reflect.Method.invoke(Method.java:577)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:829)org.testng.TestRunner.run(TestRunner.java:602)org.testng.SuiteRunner.runTest(SuiteRunner.java:437)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)org.testng.SuiteRunner.run(SuiteRunner.java:330)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)org.testng.TestNG.runSuitesLocally(TestNG.java:1176)org.testng.TestNG.runSuites(TestNG.java:1099)org.testng.TestNG.run(TestNG.java:1067)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


            <testcase
                name="regRun3"
                time="0.004"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="sanityRun2"
                time="0.003"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="regRun1"
                time="0.121"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="smokeRun2"
                time="0.004"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="sanityRun1"
                time="0.003"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="regRun2"
                time="0.003"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
            <testcase
                name="regRun4"
                time="0.004"
                classname="RESTAssuredAPIAutomation.TestNG.Groups">
            </testcase>
</testsuite>
